import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { TopSearch, Navbar } from "@components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ar" dir="rtl">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center justify-between">
          <TopSearch />
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
